version: '3.3'

services:
  zeebe:
    build:
      context: ./exporter
      dockerfile: Dockerfile
      labels:
        io.zeebe.exporter.kafka: "Zeebe Kafka Exporter"
    container_name: zeebe
    hostname: zeebe
    depends_on:
      - kafka
    ports:
      - "26500:26500"
    restart: always

  consumer:
    build:
      context: ./samples
      dockerfile: Dockerfile
      labels:
        io.zeebe.exporter.kafka: "Zeebe Kafka Consumer"
    container_name: consumer
    hostname: consumer
    depends_on:
      - kafka
      - zookeeper
    restart: always
    environment:
      KAFKA_HOST: "kafka:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
